ASSUME CS:CODE,DS:DATA
DATA SEGMENT
    HEX DW 0AAFH
    COUNTER DB 00H
DATA ENDS
CODE SEGMENT
START:  MOV AX,DATA
        MOV DS,AX
        MOV AX,HEX
        MOV BX,000AH
        MOV DX,0000H
L:  INC COUNTER
    DIV BX
    PUSH DX
    CMP AX,0000H
    MOV DX,00H
    JE EXIT
    JMP L
EXIT:  MOV CL, COUNTER
       MOV CH,00H
L1:  POP DX
    ADD DL,30H
    MOV AH,02H
    INT 21H
    LOOP L1
    MOV AH,4CH
    INT 21H
CODE ENDS
  END START