DATA SEGMENT
	LIST DB 00H,7FH,80H,0FFH
	COUNT EQU 04H
	LARGEST DB 01H DUP(0)
DATA ENDS
CODE SEGMENT
	ASSUME CS:CODE,DS:DATA
  START:MOV AX,DATA
	MOV DS,AX
	MOV AX,0000H
	LEA SI,LIST
	MOV CX,COUNT-1
	MOV AL,[SI]
     L2:CMP AL,[SI+1]
	JAE L1
	MOV AL,[SI+1]
     L1:INC SI
	LOOP L2
	MOV LARGEST,AL
	MOV AH,4CH
	INT 21H
	CODE ENDS
  END START